/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.cwl.avro;
@org.apache.avro.specific.AvroGenerated
public enum PrimitiveType implements org.apache.avro.generic.GenericEnumSymbol<PrimitiveType> {
  null$, boolean$, int$, long$, float$, double$, string  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PrimitiveType\",\"namespace\":\"io.cwl.avro\",\"symbols\":[\"null\",\"boolean\",\"int\",\"long\",\"float\",\"double\",\"string\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
