name: CWL Avro Testing
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
   # upgrade pip?
      - run: sudo pip install --upgrade pip
   # install a specific version of the cwl dependencies to test with
      - run: pip3.10 install --user setuptools==69.0.2
      - run: pip3.10 install --user cwl-runner cwltool==3.1.20230201224320 schema-salad==8.4.20230201194352
      - run: git clone https://github.com/common-workflow-language/common-workflow-language
   # convert CWL schema salad CWL to standard Avro json
      - run: schema-salad-tool --print-avro common-workflow-language/v1.0/CommonWorkflowLanguage.yml  > cwl.avsc
   # get rid of invalid avro symbols
      - run: sed '/draft-3/d' cwl.avsc > cwl.edited.avsc
      - run: sed -i '/draft-2/d' cwl.edited.avsc
      - run: sed -i '/draft-4/d' cwl.edited.avsc
      - run: sed -i '/dev4/d' cwl.edited.avsc
      - run: sed -i '/v1.0/d' cwl.edited.avsc
      # Replace the namespace generated by schema-salad-tool with our namespace, "io.cwl.avro" so
      # that the generated Java models will have this package name.
      - run: sed -i 's/org.w3id.cwl.cwl/io.cwl.avro/g' cwl.edited.avsc
      - run: sed -i 's/org.w3id.cwl.salad/io.cwl.avro/g' cwl.edited.avsc
   # get rid of symbols that screw up javadoc (not sure if invalid avro schema)
      - run: sed -i 's/<A>/A/g' cwl.edited.avsc
      - run: sed -i 's/<B>/B/g' cwl.edited.avsc
      - run: sed -i 's/<C>/C/g' cwl.edited.avsc
      - run: wget https://repo1.maven.org/maven2/org/apache/avro/avro-tools/1.11.3/avro-tools-1.11.3.jar
   # generate Java model classes.
      - run: java -jar avro-tools-1.11.3.jar compile schema cwl.edited.avsc cwl-temp
      - run: find cwl-temp/ -type f -exec sed -i 's/Any/Object/g' {} \;
      - run: mv cwl-temp/io/cwl/avro/Any.java cwl-temp/io/cwl/avro/Object.java 
    # There are 5 subdirectories in cwl-temp/io/cwl/avro that have the same name as a file
    # Fix ArraySchema conflict
      - run: mv cwl-temp/io/cwl/avro/ArraySchema cwl-temp/io/cwl/avro/ArraySchemaPackage
      - run: find cwl-temp/ -type f -exec sed -i 's/io.cwl.avro.ArraySchema/io.cwl.avro.ArraySchemaPackage/g' {} \;
    # Fix Directory conflict
      - run: mv cwl-temp/io/cwl/avro/Directory cwl-temp/io/cwl/avro/DirectoryPackage
      - run: find cwl-temp/ -type f -exec sed -i 's/io.cwl.avro.Directory/io.cwl.avro.DirectoryPackage/g' {} \;
    # Fix EnumSchema conflict
      - run: mv cwl-temp/io/cwl/avro/EnumSchema cwl-temp/io/cwl/avro/EnumSchemaPackage
      - run: find cwl-temp/ -type f -exec sed -i 's/io.cwl.avro.EnumSchema/io.cwl.avro.EnumSchemaPackage/g' {} \;
    # Fix File conflict
      - run: mv cwl-temp/io/cwl/avro/File cwl-temp/io/cwl/avro/FilePackage
      - run: find cwl-temp/ -type f -exec sed -i 's/io.cwl.avro.File/io.cwl.avro.FilePackage/g' {} \;
    # Fix RecordSchema conflict
      - run: mv cwl-temp/io/cwl/avro/RecordSchema cwl-temp/io/cwl/avro/RecordSchemaPackage
      - run: find cwl-temp/ -type f -exec sed -i 's/io.cwl.avro.RecordSchema/io.cwl.avro.RecordSchemaPackage/g' {} \;
    # Copy generated java classes
      - run: rm -Rf cwlavro-generated/src/main/java/io/cwl/avro/*
      - run: cp -R cwl-temp cwlavro-generated/src/main/java/io/cwl/avro
      - run: echo "the output below should show that the generated API more-or-less matches the checked-in API for convenience"
      - run: git diff

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.4+8'
          distribution: 'adopt'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java   

      - run: mvn -B clean install


      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
